Initial project setup
nganifaith/React_Calculator pull request #1
Opened 2021-07-25 20:01 UTC by nganifaith

This request contains the initial project setup and development for Heroku.

2021-07-26 19:37 UTC, george-shammar requested changes
Hi Faith, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code. :pray: 

## Invalid Code Review Request :red_circle: 

You have submitted a project without a custom README. 
Friendly reminder: You should make sure that your repo looks professional before review.
Please take a step back and read a [lesson here.](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
Then apply 3 simple rules from this lesson (it will be easy as you can use a template provided there).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-07-26 22:19 UTC, george-shammar commented on src/reportWebVitals.js
>        getFCP(onPerfEntry);
- [ ] Let's remove unnecessary boiler plate files created by create-react-app. As per the project requirement, unnecessary files or assets, such as the React svg Logo should be deleted.

2021-07-26 22:24 UTC, george-shammar requested changes
Hi Faith, 

Good job so far! :clap:
 
You're on your way to creating a cool application. :+1: 

There are some issues that you still need to work on to go to the next milestone but you are almost there!

## Required Changes ♻️
_Check the comments under the review section as well._

- [x] Unnecessary files or assets, such as the React svg Logo, should be deleted. `setupTests.js`, `App.test.js`, `reportWebVitals.js` and all image files all belong to this category.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-07-27 10:33 UTC, nganifaith commented
> Hi Faith,
> 
> Good job so far! 👏
> 
> You're on your way to creating a cool application. 👍
> 
> There are some issues that you still need to work on to go to the next milestone but you are almost there!
> 
> ## Required Changes ♻️
> _Check the comments under the review section as well._
> 
> * [x]  Unnecessary files or assets, such as the React svg Logo, should be deleted. `setupTests.js`, `App.test.js`, `reportWebVitals.js` and all image files all belong to this category.
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

@george-shammar  thank you for your review. Some of these files mentioned will be necessary for my project. reportWebVital.js will be for performance in my application. 

- setupTests.js will be used in testing my application. 
- Finally, I am using the logo in my index.html

2021-07-27 10:52 UTC, rindrajosia approved these changes
Hi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-07-27 13:05 UTC, merged